#!/usr/bin/env python3
"""Fail the docs build if a nav/TOC button points at an id the page does not have.

WHY THIS EXISTS. The four Python-API pages (docs/python/{bundle,render,ucid,cli}.md) are
generated by mkdocstrings, and each carries the same copy-pasted render option:

    show_root_heading: false

overriding the `true` set globally in mkdocs.yml. Whether the module-level ids
(`#aigovops_lantern.<module>`) are emitted at all is therefore governed by one shared option on
four pages — so if it ever stops emitting them, every nav button on all four pages goes dead at
once. That is one defect wearing eighteen faces, and it is exactly the shape that gets reported as
eighteen separate bugs.

They are emitted today — this guard passes on the current build, 58 anchor links across 12 pages.
It is not a fix for anything currently broken; it makes the renderer contract *enforceable*, so a
future mkdocstrings upgrade or a copy-pasted option change fails the build here instead of
shipping a page of buttons that do not move and waiting for a crawler to notice an hour later.
`mkdocs build --strict` already fails on a broken *link*; it does not check that an in-page
*anchor* has a target.

Stdlib only, deliberately: the docs toolchain should not grow a dependency to check itself.

    python scripts/check_doc_anchors.py [site_dir]      # default: site

Exit 0 when every anchor resolves; exit 1 naming each dead one.
"""

from __future__ import annotations

import sys
from html.parser import HTMLParser
from pathlib import Path
from urllib.parse import unquote, urldefrag

# Only the module-anchor class this guard is about. A dead `#installation` is a content typo and
# --strict's link checking is the right place for it; a dead `#aigovops_lantern.*` is the renderer
# contract silently changing under us, which is what we cannot afford to learn from a crawler.
PREFIX = "aigovops_lantern"


class _Page(HTMLParser):
    """Collect every element id, and every href that targets a PREFIX anchor."""

    def __init__(self) -> None:
        super().__init__(convert_charrefs=True)
        self.ids: set[str] = set()
        self.links: list[str] = []

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        a = dict(attrs)
        # An id anywhere counts as a target: mkdocstrings puts them on headings, but also on bare
        # <a>/<span> anchors, and a heading is not the only legal landing place.
        if a.get("id"):
            self.ids.add(a["id"])
        # <a name="..."> is the pre-HTML5 form and still a valid target.
        if tag == "a" and a.get("name"):
            self.ids.add(a["name"])
        href = a.get("href")
        if href and "#" + PREFIX in unquote(href):
            self.links.append(unquote(href))


def _parse(path: Path) -> _Page:
    p = _Page()
    p.feed(path.read_text(encoding="utf-8", errors="replace"))
    return p


def check(site: Path) -> list[str]:
    """Return a list of human-readable problems; empty means every anchor resolves."""
    pages = sorted(site.rglob("*.html"))
    if not pages:
        return [f"no HTML found under {site} — did `mkdocs build` run?"]

    parsed = {p: _parse(p) for p in pages}
    problems: list[str] = []
    checked = 0

    for page, doc in parsed.items():
        for href in doc.links:
            target, frag = urldefrag(href)
            if not frag:
                continue
            checked += 1
            # An in-page href ("#x") resolves against this page; a relative one ("../mod/#x")
            # resolves against the page it names, so the id must exist THERE.
            if target in ("", "."):
                owner, owner_doc = page, doc
            else:
                resolved = (page.parent / target).resolve()
                if resolved.is_dir():
                    resolved = resolved / "index.html"
                owner_doc = parsed.get(resolved)
                owner = resolved
                if owner_doc is None:
                    # A link off-site or to a non-built path is not this guard's business;
                    # --strict already governs whether the link itself is valid.
                    checked -= 1
                    continue
            if frag not in owner_doc.ids:
                problems.append(
                    f"{page.relative_to(site)}: button points at #{frag} "
                    f"but {owner.relative_to(site) if owner != page else 'that page'} has no element with that id"
                )

    print(f"checked {checked} #{PREFIX}* anchor link(s) across {len(pages)} page(s)")
    return problems


def main(argv: list[str]) -> int:
    site = Path(argv[0] if argv else "site")
    if not site.exists():
        print(f"anchor guard: {site} does not exist — run `mkdocs build` first", file=sys.stderr)
        return 1
    problems = check(site)
    if problems:
        print(
            f"\nanchor guard FAILED — {len(problems)} dead #{PREFIX}* button(s).\n"
            "Each is a nav/TOC link whose target id is not in the built HTML. The usual cause is a\n"
            "mkdocstrings render option (show_root_heading / heading levels) changing which ids get\n"
            "emitted. Fix the renderer so the ids are emitted, not the links.\n",
            file=sys.stderr,
        )
        for p in problems:
            print(f"  ✗ {p}", file=sys.stderr)
        return 1
    print(f"anchor guard OK — every #{PREFIX}* button has a matching id")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
